services:
  postgres:
    container_name: postgres-db
    image: postgres:15-alpine 
    restart: always
    environment:
      - LC_ALL=C.UTF-8
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    env_file:
      - .env.prod

  web: &web
    container_name: technical_task_web
    build: .
    env_file:
      - .env.prod
    volumes:
      - ./app:/code
      - ./app/static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  nginx:
    image: jwilder/nginx-proxy
    container_name: technical_task_nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/sites/technical_task.com.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/sites/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./app/static:/code/static
    ports:
      - "80:80"
    depends_on:
      - web 

volumes:
  db:

networks:
  nginx-proxy:
    external: true
